language: ruby
sudo: false
matrix:
  include:
  - rvm: 2.1
    gemfile: "gemfiles/Gemfile.ruby-2.1"
  - rvm: 2.2
    gemfile: "gemfiles/Gemfile.ruby-2.2"
  - rvm: 2.3.1
    gemfile: "gemfiles/Gemfile.ruby-2.3.1"
script:
  - bundle exec rake
branches:
  except:
    - release
notifications:
  email: false
